version: '3.7'
services:
  mysql:
    image: mysql:8.0.19
    restart: always
    ports:
      - '3306:3306'
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=psw5432

  postgres:
    image: postgres:12.0-alpine
    restart: always
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_RANDOM_ROOT_PASSWORD=yes
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=psw5432

  nodejs:
    build: ./gate-simulator
    ports:
      - '9999:9999'